from chessAI.modelHyperParameters.linear.logisticRegression import get_list_model_parameters_LogisticRegression
from chessAI.modelHyperParameters.linear.linearNN1 import get_list_model_parameters_LinearNN1
from chessAI.modelHyperParameters.linear.linearNN2 import get_list_model_parameters_LinearNN2
from chessAI.modelHyperParameters.linear.linearNN3 import get_list_model_parameters_LinearNN3
from chessAI.modelHyperParameters.linear.linearNN4 import get_list_model_parameters_LinearNN4
from chessAI.modelHyperParameters.linear.linearNN5 import get_list_model_parameters_LinearNN5